export const projecsData = [
  {
    id: 1,
    name: "Control Finance",
    description: "Mini aplicativo para controle de finanças pessoais",
    img: "https://i.ibb.co/yPxJX3d/1.png",
    homepage: "https://kellygalliani.github.io/ControleFinanceiro/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/ControleFinanceiro",
    language: ["Javascript", "Html", "Css"],
  },
  {
    id: 2,
    name: "Open Music",
    description:
      "Treinando o dak-mode theme e filtragem por botões e pelo input range",
    img: "https://i.ibb.co/sjfDtnT/3.png",
    homepage: "https://kellygalliani.github.io/open-music-base/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/open-music-base",
    language: ["Javascript", "Html", "Css"],
  },
  {
    id: 3,
    name: "Web Woman",
    description: "Plataforma de empregos na área de TI para mulheres",
    img: "https://i.ibb.co/8DPFHFj/5.png",
    homepage:
      "https://kellygalliani.github.io/webwomen-job-plataform/pages/home/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/webwomen-job-plataform",
    language: ["Javascript", "Html", "Css"],
  },
  {
    id: 4,
    name: "Git Search",
    description:
      "Encontre e se conecte com profissionais no github de forma rápida e fácil",
    img: "https://i.ibb.co/FXGTW4k/2.png",
    homepage: "https://kellygalliani.github.io/GitSearchBase/pages/home/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/GitSearchBase",
    language: ["Javascript", "Html", "Css"],
  },
  {
    id: 5,
    name: "Kenzie Hub",
    description:
      "Encontre e se conecte com profissionais no github de forma rápida e fácil",
    img: "https://i.ibb.co/YXV0HpZ/7.png",
    homepage: "https://react-entrega-kenzie-hub-kellygalliani.vercel.app/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/kenzie-hub",
    language: ["React", "Javascript"],
  },
  {
    id: 6,
    name: "Hamburguer Shop",
    description:
      "Hamburgueria On-line com opções avançadas - inserir no carrinho, incrementar quantidade, filtrar",
    img: "https://i.ibb.co/dmCS5rw/4.png",
    homepage: "https://react-entrega-hamburgueria-v2-kelly.vercel.app/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/hamburgueria-v2-Typescript",
    language: ["React", "Typescript"],
  },
  {
    id: 7,
    name: "API - Gerenciamento de usuários",
    description:
      "Api Restfull criada para gerenciar a autenticação de diferentes tipos de usuários",
    img: "https://i.ibb.co/pwqnbV8/6.png",
    homepage: "",
    documentation: "https://doc-api-adm.vercel.app/",
    html_url:
      "https://github.com/kellygalliani/API-RESTfull-crud-users-authentication",
    language: ["Node.js", "Express", "Typescript"],
  },
  {
    id: 8,
    name: "API - Filmay - Banco de Filmes  ",
    description:
      "Um gerenciador de filme no estilo do aplicativo Filmow - É possível cadastrar, visualizar os filmes, atualizar informações do filme e deletar",
    img: "https://i.ibb.co/kBCjCzt/10.png",
    homepage: "",
    documentation: "",
    html_url: "https://github.com/kellygalliani/movies-typeorm",
    language: ["Node.js", "Express", "Typescript", "TypeORM"],
  },
  {
    id: 9,
    name: "API - Nostra Imóveis",
    description: "Api para gerenciamento completo de uma imobiliária",
    img: "https://i.ibb.co/LPZFN9N/9.png",
    homepage: "",
    documentation: "",
    html_url: "https://github.com/kellygalliani/m4-t14-kimoveis-kelly",
    language: ["Node.js", "Express", "Typescript", "TypeORM"],
  },
  {
    id: 10,
    name: "API - KGP Commerce",
    description: "Api completa para gerenciamento de um e-commerce",
    img: "https://i.ibb.co/8zHRNxN/8.png",
    homepage: "",
    documentation: "https://ecommerce-g35.onrender.com/api/docs/swagger/",
    html_url: "https://github.com/kellygalliani/ecommerce-api_python",
    language: ["Python", "Django"],
  },
];
