export const projecsData = [
  {
    id: 1,
    name: "Control Finance",
    description: "Mini aplicativo para controle de finanças pessoais",
    img: "../public/static/img/controle_finance.jpg",
    homepage: "https://kellygalliani.github.io/ControleFinanceiro/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/ControleFinanceiro",
    language: ["Javascript", "Html", "Css"],
  },
  {
    id: 2,
    name: "Open Music",
    description:
      "Treinando o dak-mode theme e filtragem por botões e pelo input range",
    img: "../public/static/img/open_music.jpg",
    homepage: "https://kellygalliani.github.io/open-music-base/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/open-music-base",
    language: ["Javascript", "Html", "Css"],
  },
  {
    id: 3,
    name: "Web Woman",
    description: "Plataforma de empregos na área de TI para mulheres",
    img: "../public/static/img/woman.jpg",
    homepage:
      "https://kellygalliani.github.io/webwomen-job-plataform/pages/home/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/webwomen-job-plataform",
    language: ["Javascript", "Html", "Css"],
  },
  {
    id: 4,
    name: "Git Search",
    description:
      "Encontre e se conecte com profissionais no github de forma rápida e fácil",
    img: "../public/static/img/git_search.jpg",
    homepage: "https://kellygalliani.github.io/GitSearchBase/pages/home/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/GitSearchBase",
    language: ["Javascript", "Html", "Css"],
  },
  {
    id: 5,
    name: "Kenzie Hub",
    description:
      "Encontre e se conecte com profissionais no github de forma rápida e fácil",
    img: "../public/static/img/kenzie_hub.jpg",
    homepage: "https://react-entrega-kenzie-hub-kellygalliani.vercel.app/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/kenzie-hub",
    language: ["React", "Javascript"],
  },
  {
    id: 6,
    name: "Hamburguer Shop",
    description:
      "Hamburgueria On-line com opções avançadas - inserir no carrinho, incrementar quantidade, filtrar",
    img: "../public/static/img/kenzie_burguer.jpg",
    homepage: "https://react-entrega-hamburgueria-v2-kelly.vercel.app/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/hamburgueria-v2-Typescript",
    language: ["React", "Typescript"],
  },
  {
    id: 7,
    name: "API - Gerenciamento de usuários",
    description:
      "Api Restfull criada para gerenciar a autenticação de diferentes tipos de usuários",
    img: "../public/static/img/code.jpg",
    homepage: "",
    documentation: "https://doc-api-adm.vercel.app/",
    html_url:
      "https://github.com/kellygalliani/API-RESTfull-crud-users-authentication",
    language: ["Node.js", "Express", "Typescript"],
  },
  {
    id: 8,
    name: "API - Filmay - Banco de Filmes  ",
    description:
      "Um gerenciador de filme no estilo do aplicativo Filmow - É possível cadastrar, visualizar os filmes, atualizar informações do filme e deletar",
    img: "../public/static/img/code.jpg",
    homepage: "",
    documentation: "",
    html_url: "https://github.com/kellygalliani/movies-typeorm",
    language: ["Node.js", "Express", "Typescript", "TypeORM"],
  },
  {
    id: 9,
    name: "API - Nostra Imóveis",
    description: "Api para gerenciamento completo de uma imobiliária",
    img: "../public/static/img/code.jpg",
    homepage: "",
    documentation: "",
    html_url: "https://github.com/kellygalliani/m4-t14-kimoveis-kelly",
    language: ["Node.js", "Express", "Typescript", "TypeORM"],
  },
  {
    id: 10,
    name: "API - KGP Commerce",
    description: "Api completa para gerenciamento de um e-commerce",
    img: "../public/static/img/code.jpg",
    homepage: "",
    documentation: "https://ecommerce-g35.onrender.com/api/docs/swagger/",
    html_url: "https://github.com/kellygalliani/ecommerce-api_python",
    language: ["Python", "Django"],
  },
  {
    id: 11,
    name: "FreshCodes - Site Institucional",
    description:
      "Criação de +8 páginas para site institucional, com modais, lógica de contagem regressiva em javascript, observer e tudo em Tailwind",
    img: "../public/static/img/fresh.jpg",
    homepage: "https://freshcodes.com.br/",
    documentation: "",
    html_url: "",
    language: ["Html", "Tailwind", "JS", "PHP"],
  },
  {
    id: 12,
    name: "SG Global Group - Site Institucional",
    description:
      "Funções em PHP para busca em banco de dados, observer para ações específicas em dobras do site e animações em css (carrosel infinito de imagens)",
    img: "../public/static/img/sg_site.jpg",
    homepage: "https://sgglobal.group/",
    documentation: "",
    html_url: "",
    language: ["Html", "Bootstrap", "CSS", "JS", "PHP"],
  },
  {
    id: 13,
    name: "Creative - Plataforma de Educação",
    description: "Plataforma de Educação Digital - Com Lousa Digital",
    img: "../public/static/img/creative.jpg",
    homepage: "https://creative-educ-angular.vercel.app/",
    documentation: "",
    html_url: "https://github.com/kellygalliani/creative_educ-angular",
    language: ["Angular", "JS", "CSS"],
  },
  {
    id: 13,
    name: "SG MONITOR - Gerenciamento Interno",
    description:
      "Plataforma de gerenciamento de todos os setores internos e dashboards da empresa",
    img: "../public/static/img/sg_monitor.jpg",
    homepage: "",
    documentation: "",
    html_url: "",
    language: ["Flutter"],
  },
  {
    id: 14,
    name: "App - Torcidale",
    description:
      "Plataforma inovadora dedicada aos torcedores de futebol, que combina rede social com gamificação",
    img: "../public/static/img/torcidale.jpg",
    homepage: "",
    documentation: "",
    html_url: "",
    language: ["Flutter", "Android", "IOS"],
  },
];
